---
title: "Interpretacao"
author: "JoaoPaulo"
date: "9 de abril de 2019"
output: html_document
---

## **Métricas para avaliar os algoritmos de Aprendizado de Máquina utilizados na ferramenta** <br>
<hr>

- [Algoritmos de Classificação](#class)
- [Tabelas Classificação](#tabclass)
- [Gráficos Classificação](#grafclass)
<br>
- [Algoritmos de Regressão](#reg)
- [Tabelas Regressão](#tabreg)
- [Gráficos Regressão](#grafreg)


<hr>

### <a id="class"></a>**Algoritmos de Classificação** <br>
<br>

#### <a id="tabclass"></a>Tabelas

**Executando os modelos da ferramenta, é produzida a tabela contendo os valores de Acurácia para cada algoritmo de aprendizado de máquina avaliado.** <br>
<br>

**Também é produzida a tabela, onde são gerados os resultados da Matriz de Confusão gerada no conjunto de teste do modelo, por classe.** <br> <br>

É importante compreender algumas terminologias de classificação. Vamos utilizar o exemplo de um classificador binário (classificar se um e-mail é ou não spam):

- Verdadeiro Positivo $(VP)$ : significa uma classificação correta de SPAM. Por exemplo, o email era SPAM e o modelo classificou como SPAM. <br>
- Verdadeiro Negativo $(VN)$ : significa uma classificação correta da classe negativa. Por exemplo, o email era comum e o modelo classificou como comum. <br>
- Falso Positivo $(FP)$ : significa uma classificação errada da classe positiva. Por exemplo, o email é comum e o modelo classificou como SPAM.
- Falso Negativo $(FN)$ : significa uma classificação errada da classe negativa. Por exemplo, o email é SPAM e o modelo classificou como comum.

Dessa forma podemos definir:

- **Acurácia** (*Accuracy*):
Acurácia = $\frac {(VP + VN)}{(VP + VN + FP + FN)}$ <br>

Mostra a quantidade de acertos sobre um todo, nos mostrando como o classificador se saiu de maneira geral. É mais útil em uma classificação binária do que problemas de classificação de várias classes, pois pode ser menos claro exatamente como a acurácia se divide nessas classes (por exemplo, você precisa ir mais fundo em uma matriz de confusão, que também é disponibilizada na ferramenta). <br>


- **Sensibilidade** (*Sensibility*):
Denota a proporção de casos positivos que foram identificados corretamente. <br>

- **Especificidade** (*Specificity*):
Denota a proporção de casos negativos que foram identificados corretamente. <br>

- **Precisão** (*Precision*):
Precisão = $\frac {(VP)} {(VP + FP)}$ <br>
É a proporção de verdadeiros positivos sobre todos os resultados positivos. <br>

- **Revocação** (*Recall*):
Revocação = $\frac {(VP)}{(VP + FN)}$ <br>
A revocação é a frequência em que o classificador encontra os exemplos de uma classe, ou seja, “quando realmente é da classe A, o quão frequente classifica-se como A?” <br>

- **F1**:
F1 = $\frac {2 * (Precisão * Revocação)} {(Precisão + Revocação)}$ <br>
É a média harmônica entre precisão e revocação. Com essa informação podemos expressar a performance do classificador com um indicador apenas. Como essa medida é uma média, nos dá uma visão mais exata da eficiência do classificador do que apenas a precisão ou a revocação. Em geral, quanto mais próximo de 1, melhor. <br>

<br> 


#### <a id="grafclass"></a>Gráficos


- **Métrica x Hiperparâmetro**:
Gráfico disponível quando a opção *Padrão* de Parâmetros do Modelo for selecionada. Mostra a relação entre a métrica obtida e os hiperparâmetros selecionados. <br>

- **Importância das Variáveis**:
Este gráfico mostra a importância que cada variável independente teve no modelo. Ou seja, caso seu modelo possua muitas variáveis independentes com baixa importância nos resultados, convém, geralmente retirá-las do modelo e retreiná-lo utilizando apenas variáveis de alta importância. <br>

- **Matriz de Confusão - Teste**:
Mostra a relação entre os valores reais e os valores preditos, classe a classe, tendo em um eixo a referência, e no outro o resultado. A diagonal da matriz, contém os valores acertados pelo modelo.<br>

- **Região de Decisão**:
Gráfico disponível quando selecionadas apenas *duas* variáveis independentes. Mostra, no treino, qual foi a área de decisão do algoritmo selecionado para classificar os alvos escolhidos. Este gráfico é importante para observar o comportamento do modelo e compará-lo com os demais (modelos lineares vs modelos não lineares por exemplo).<br>

- **Limite de Decisão**:
Gráfico disponível quando selecionadas apenas *duas* variáveis independentes. Mostra, o limite de decisão que o algoritmo criou para classificar os alvos escolhidos. Além disso, os pontos observados referem-se aos pontos preditos do conjunto de teste. Desta forma, convém analisar, em conjunto, a Matriz de Confusão, a Região de Decisão e o Limite de Decisão para interpretar os resultados. <br>





<hr>

### <a id="reg"></a>**Algoritmos de Regressão**
<br>

#### <a id="tabreg"></a>Tabelas 

**Executando os modelos da ferramenta, é produzida a tabela contendo os valores de Rsquared e RMSE  para cada algoritmo de aprendizado de máquina avaliado.** <br>


- **Raiz Quadrada do Erro Quadrático Médio** (*RMSE - Root Mean Squared Error*):
A Raiz Quadrada do Erro Quadrático Médio ou simplesmente RMSE, nada mais é que a diferença entre o valor que foi previsto pelo seu modelo e o valor real que foi observado, e é mostrada na unidade da variável dependente. Ela é utilizada para obter uma ideia geral do quão bem (ou não) um algoritmo está ajustado.<br>

- **R²** *(Rsquared)*:
O R quadrado, ou coeficiente de determinação fornece uma medida de quão bem o modelo foi ajustado em relação aos novos dados. É um valor entre 0 e 1, sendo 0 para nenhum ajuste e 1 para ajuste perfeito.<br>


 <br>

 <br> 


#### <a id="grafreg"></a>Gráficos
<br>

- **Resultados do Conjunto de Teste**:
Este gráfico está disponível quando seleciona apenas **uma** variável independente. Ele mostra como o modelo gerado se ajustou quando aplicado aos dados do conjunto de teste (ainda não conhecidos pelo modelo). Os pontos na cor magenta referem-se aos pontos do conjunto de teste, enquanto que a linha ou curva em azul refere-se ao resultado obtido pelo modelo. <br>


- **Métrica x Hiperparâmetro**:
Gráfico disponível quando a opção *Padrão* de Parâmetros do Modelo for selecionada. Mostra a relação entre a métrica obtida e os hiperparâmetros selecionados. <br>

- **Importância das Variáveis**:
Este gráfico mostra a importância que cada variável independente teve no modelo. Ou seja, caso seu modelo possua muitas variáveis independentes com baixa importância nos resultados, convém, geralmente retirá-las do modelo e retreiná-lo utilizando apenas variáveis de alta importância. <br>

- **Relação das Variáveis**:
Este gráfico mostra a relação entre as variáveis independentes do modelo e a variável dependente, através de um gráfico de dispersão. Convém analisar em conjunto o gráfico de Importância das Variáveis e Relação das Variáveis para interpretar melhor os resultados obtidos.
<br>

<hr>